<div style="width:100%; background-color:#181818; color:#f1f1f1; padding:30px 0; text-align:center; border-radius:10px;">

  <img src="https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExcXVodWNsM3Bia3duZGljZzRqMTI2MGFiZjlkZzBwcmhuaWxydjlpaiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/AOSwwqVjNZlDO/giphy.gif" alt="Beam Oscillation" width="400" style="border-radius:10px;">

  <h3 style="color:#ffffff; margin-top:15px;"><b>Solution Example of Truss Element</b></h3>

  <p><b>Author:</b> <a href="http://caceli.net/" style="color:#3ea6ff; text-decoration:none;">Msc. Ing. Carlos Andrés Celi Sánchez</a></p>
  <p><b>Course:</b> Matrix Analisys</p>
  <p><b>Year:</b> MAYO - 2026</p>

</div>

#### Libraries

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from repo_maxtrix_analisys import *

#### Case
![alt text](image-12.png)

#### Data

In [11]:
E = 21000000
l = 3
L = [l,l,l*np.sqrt(2),l*np.sqrt(2),l,l]
thethas = [0,90,135,45,90,0]
db = 0.018
A = np.pi * db**(2) / 4
local_dof = 2                                                                                                       # Local DOF per element
Global_dof = 4                                                                                                      # Local DOF per element

#### Solution

##### Stiffness Matrix in Local Coordinates

In [12]:
# --- Create structure container -----------------------------------------------------------------------------------
structure = Manager_K_T_elements2D(method= 'ARM')                                                                                       # Create an instance of the MF structure

# --- Add ARM elements to the structure -----------------------------------------------------------------------------
for i in np.arange(0, len(thethas), 1):                                                                                      # Loop to add each element
    structure.add_element(ARM_K_T_Element2D(E = E,A = A, L = L[i], thetha= thethas[i]))

In [13]:
# --- Stack local stiffness matrices --------------------------------------------------------------------------------
K_all = structure.stacked_stiffness_matrices()                                                                      # Stacked stiffness matrix (2N x 2)

# --- Convert to DataFrame for visualization -----------------------------------------------------------------------
n_elem = len(structure.elements)
n_dof  = local_dof

rows = pd.MultiIndex.from_tuples(
    [(f'Elem_{e+1}', f'DOF_L_{d+1}') for e in range(n_elem) for d in range(n_dof)],
    names=['Element', 'Local DOF']
)

K_all_df = pd.DataFrame(K_all, index=rows, columns=[f'DOF_L_{i}' for i in np.arange(1, K_all.shape[1] + 1)])        # Convert to DataFrame for better visualization
K_all_df.head(len(K_all_df))                                                                                        # Display stacked matrices

                       DOF_L_1      DOF_L_2
Element Local DOF
Elem_1  DOF_L_1    1781.283035 -1781.283035
        DOF_L_2   -1781.283035  1781.283035
Elem_2  DOF_L_1    1781.283035 -1781.283035
        DOF_L_2   -1781.283035  1781.283035
Elem_3  DOF_L_1    1259.557313 -1259.557313
        DOF_L_2   -1259.557313  1259.557313
Elem_4  DOF_L_1    1259.557313 -1259.557313
        DOF_L_2   -1259.557313  1259.557313
Elem_5  DOF_L_1    1781.283035 -1781.283035
        DOF_L_2   -1781.283035  1781.283035
Elem_6  DOF_L_1    1781.283035 -1781.283035
        DOF_L_2   -1781.283035  1781.283035

##### Transformation Matrix

In [14]:
# --- Stack Transformation matrices --------------------------------------------------------------------------------
T_all = structure.stacked_transformation_matrices()                                                                 # Stacked transformation matrix (4N x 2)

# --- Convert to DataFrame for visualization -----------------------------------------------------------------------
n_dof  = Global_dof
rows = pd.MultiIndex.from_tuples(
    [(f'Elem_{e+1}', f'DOF_L_G_{d+1}') for e in range(n_elem) for d in range(n_dof)],
    names=['Element', 'Local - Global DOF']
)

T_all_df = pd.DataFrame(T_all, index=rows, columns=['Column 1', 'Column 2'])                                        # Convert to DataFrame for better visualization
T_all_df.head(len(T_all_df))                                                                                        # Display stacked matrices

                                Column 1      Column 2
Element Local - Global DOF
Elem_1  DOF_L_G_1           1.000000e+00  0.000000e+00
        DOF_L_G_2           0.000000e+00  0.000000e+00
        DOF_L_G_3           0.000000e+00  1.000000e+00
        DOF_L_G_4           0.000000e+00  0.000000e+00
Elem_2  DOF_L_G_1           6.123234e-17  0.000000e+00
        DOF_L_G_2           1.000000e+00  0.000000e+00
        DOF_L_G_3           0.000000e+00  6.123234e-17
        DOF_L_G_4           0.000000e+00  1.000000e+00
Elem_3  DOF_L_G_1          -7.071068e-01  0.000000e+00
        DOF_L_G_2           7.071068e-01  0.000000e+00
        DOF_L_G_3           0.000000e+00 -7.071068e-01
        DOF_L_G_4           0.000000e+00  7.071068e-01
Elem_4  DOF_L_G_1           7.071068e-01  0.000000e+00
        DOF_L_G_2           7.071068e-01  0.000000e+00
        DOF_L_G_3           0.000000e+00  7.071068e-01
        DOF_L_G_4           0.000000e+00  7.071068e-01
Elem_5  DOF_L_G_1           6.123234e-17  0.000000e+00
        DOF_L_G_2           1.000000e+00  0.000000e+00
        DOF_L_G_3           0.000000e+00  6.123234e-17
        DOF_L_G_4           0.000000e+00  1.000000e+00
Elem_6  DOF_L_G_1           1.000000e+00  0.000000e+00
        DOF_L_G_2           0.000000e+00  0.000000e+00
        DOF_L_G_3           0.000000e+00  1.000000e+00
        DOF_L_G_4           0.000000e+00  0.000000e+00

##### Stiffness Matrix in Global Coordinates

In [18]:
Keg_all = []
for i in np.arange(0,n_elem,1):
    Telem = structure.elements[i].transformation_ARM_matrix_2D()
    Kelem = structure.elements[i].stiffness_matrix_ARM_AE()
    Keg_all.append(Telem@Kelem@Telem.T)
Keg_all

[array([[ 1781.28303459,     0.        , -1781.28303459,     0.        ],
        [    0.        ,     0.        ,     0.        ,     0.        ],
        [-1781.28303459,     0.        ,  1781.28303459,     0.        ],
        [    0.        ,     0.        ,     0.        ,     0.        ]]),
 array([[ 6.67874164e-30,  1.09072128e-13, -6.67874164e-30,
         -1.09072128e-13],
        [ 1.09072128e-13,  1.78128303e+03, -1.09072128e-13,
         -1.78128303e+03],
        [-6.67874164e-30, -1.09072128e-13,  6.67874164e-30,
          1.09072128e-13],
        [-1.09072128e-13, -1.78128303e+03,  1.09072128e-13,
          1.78128303e+03]]),
 array([[ 629.77865648, -629.77865648, -629.77865648,  629.77865648],
        [-629.77865648,  629.77865648,  629.77865648, -629.77865648],
        [-629.77865648,  629.77865648,  629.77865648, -629.77865648],
        [ 629.77865648, -629.77865648, -629.77865648,  629.77865648]]),
 array([[ 629.77865648,  629.77865648, -629.77865648, -629.77865648],
        [ 629.77865648,  629.77865648, -629.77865648, -629.77865648],
        [-629.77865648, -629.77865648,  629.77865648,  629.77865648],
        [-629.77865648, -629.77865648,  629.77865648,  629.77865648]]),
 array([[ 6.67874164e-30,  1.09072128e-13, -6.67874164e-30,
         -1.09072128e-13],
        [ 1.09072128e-13,  1.78128303e+03, -1.09072128e-13,
         -1.78128303e+03],
        [-6.67874164e-30, -1.09072128e-13,  6.67874164e-30,
          1.09072128e-13],
        [-1.09072128e-13, -1.78128303e+03,  1.09072128e-13,
          1.78128303e+03]]),
 array([[ 1781.28303459,     0.        , -1781.28303459,     0.        ],
        [    0.        ,     0.        ,     0.        ,     0.        ],
        [-1781.28303459,     0.        ,  1781.28303459,     0.        ],
        [    0.        ,     0.        ,     0.        ,     0.        ]])]